name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --tag danccooper/folders2flickr:latest
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%s)"
    - name: Tag as latest
      run: docker tag danccooper/folders2flickr:latest danccooper/folders2flickr:${{ steps.date.outputs.date }}
    - name: Push images
      run: docker push danccooper/folders2flickr:${{ steps.date.outputs.date }} && docker push danccooper/folders2flickr:latest
